import Head from "next/head";
import Navbar from "@/components/navbar";
import Project from "@/components/project";

export default function Dnd() {
  return (
    <>
      <Head>
        <title>DND Character Creation Web App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-10">
        <section className="min-h-screen my-auto no-scrollbar">
          <Navbar />

          <Project
          projectName="Dungeons and Dragons Character Creation Website"/>
        </section>
      </main>
    </>
  );
}
