import Head from "next/head";
import { Inter } from "@next/font/google";
import Link from "next/link";
import {
  Timeline,
  TimelineConnector,
  TimelineContent,
  TimelineDot,
  TimelineItem,
  TimelineOppositeContent,
  TimelineSeparator,
  TreeView,
  TreeItem,
} from "@mui/lab";
import ChevronRightIcon from '@mui/icons-material/ChevronRight';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';

import { MdOutlineCatchingPokemon } from "react-icons/md";
import Image from "next/image";
import design from "../../public/pokemon-wpf/pokemonStats.gif";
import diceRoll from "../../public/dnd/dndDiceRoll.gif";
import dnd from "../../public/dnd/dnd.png";
import Navbar from "@/components/navbar";
import styles from "../styles/Home.module.css";
import { Typography } from "@mui/material";
import Project from "@/components/project";

export default function Dnd() {
  return (
    <>
      <Head>
        <title>DND Character Creation Web App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-10">
        <section className="min-h-screen my-auto no-scrollbar">
          <Navbar />

          <Project
          projectName="Dungeons and Dragons Character Creation Website"/>
        </section>
      </main>
    </>
  );
}
