import Head from "next/head";
import { Inter } from "@next/font/google";

import { AiFillTwitterCircle, AiFillLinkedin } from "react-icons/ai";
import Image from "next/image";
import deved from "../../public/dev-ed-wave.png";
import design from "../../public/design.png";
import code from "../../public/code.png";
import consulting from "../../public/consulting.png";
import Navbar from "@/components/navbar";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Samuel Anderson Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-10">
        <section className="min-h-screen">
          <Navbar/>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-red-400">Samuel Anderson</h2>
            <h3 className="text-2xl py-2">Full-Stack Software Developer</h3>
            <p className="text-md py-5 leading-8 text-gray-200">
              Current student working part-time. Check out my projects to see
              what I&apos;m all about.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-blue-400">
            <AiFillLinkedin
              href="https://www.linkedin.com/in/samuel-anderson-a26905206/"
              target="_blank"
              className="cursor-pointer"
            />
            <AiFillTwitterCircle className="cursor-pointer" />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden">
            <Image src={deved} layout="fill" objectFit="cover" />
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl pt-10 text-center">Career.Path</h3>
            <p className="text-md py-5 leading-8 text-gray-200">
              Current student working part-time. Check out my projects to see
              what I&apos;m all about.
            </p>
          </div>
          <div>
            <div className="text-center drop-shadow-[0_0px_5px_rgba(255,255,255,0.33)] shadow-lg shadow-teal-800 p-10 rounded-xl my-10">
              <Image
                className="mx-auto"
                src={design}
                width={100}
                height={100}
              />
              <h3 className="text-lg font-medium">Applications</h3>
              <p className="pt-4 pb-2">
                I create full-stack web <span className=" text-teal-700">//</span> desktop{" "}
                <span className=" text-teal-700">//</span> mobile applications
              </p>
              <h4>Tools I Use:</h4>
              <p className="text-gray-200 py-1">ASP.NET</p>
              <p className="text-gray-200 py-1">React</p>
              <p className="text-gray-200 py-1">Angular</p>
              <p className="text-gray-200 py-1">Javascript</p>
              <p className="text-gray-200 py-1">.NET MAUI</p>
              <p className="text-gray-200 py-1">Android Studio</p>
            </div>

            <div className="text-center drop-shadow-[0_0px_5px_rgba(255,255,255,0.33)] shadow-xl shadow-teal-800 p-10 rounded-xl my-10">
              <Image
                className="mx-auto"
                src={design}
                width={100}
                height={100}
              />
              <h3 className="text-lg font-medium">Beautiful Designs</h3>
              <p className="pt-4 pb-2">
                I create full-stack web
                <span className=" text-teal-700">//</span> desktop{" "}
                <span className=" text-teal-700">//</span> mobile applications
              </p>
              <h4>Tools I Use</h4>
              <p className="text-gray-200 py-1">ASP.NET</p>
              <p className="text-gray-200 py-1">React</p>
              <p className="text-gray-200 py-1">Angular</p>
              <p className="text-gray-200 py-1">Javascript</p>
              <p className="text-gray-200 py-1">.NET MAUI</p>
              <p className="text-gray-200 py-1">Android Studio</p>
            </div>

            <div className="text-center drop-shadow-[0_0px_5px_rgba(255,255,255,0.33)] shadow-xl shadow-teal-800 p-10 rounded-xl my-10">
              <Image
                className="mx-auto"
                src={design}
                width={100}
                height={100}
              />
              <h3 className="text-lg font-medium">Beautiful Designs</h3>
              <p className="pt-4 pb-2">
                I create full-stack web
                <span className=" text-teal-700">//</span> desktop{" "}
                <span className=" text-teal-700">//</span> mobile applications
              </p>
              <h4>Tools I Use</h4>
              <p className="text-gray-200 py-1">ASP.NET</p>
              <p className="text-gray-200 py-1">React</p>
              <p className="text-gray-200 py-1">Angular</p>
              <p className="text-gray-200 py-1">Javascript</p>
              <p className="text-gray-200 py-1">.NET MAUI</p>
              <p className="text-gray-200 py-1">Android Studio</p>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
