import Navbar from "@/components/navbar";
import Head from "next/head";
import Image from "next/image";
import design from "../../public/design.png";
import Link from "next/link";
import styles from "../styles/projects.module.css";
import { CatchingPokemon } from "@mui/icons-material";
import ShieldIcon from '@mui/icons-material/Shield';
import {SiPokemon} from 'react-icons/si';
import {GiFarmTractor} from 'react-icons/gi';
import{AiOutlineTrophy} from 'react-icons/ai';

export default function Projects() {
  return (
    <>
      <Head>
        <title>Samuel Anderson Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='px-10'>
        <Navbar />
        <section>

        <div>
            <Link href="/ptd" className={styles.childrenChangeOnHoverTower}>
            <div className='text-center shadow-xl shadow-teal-800 p-10 rounded-xl my-10 flex items-center justify-center h-96 flex-col'>
              <SiPokemon className="mx-auto text-3xl w-40 h-40"/>
              <h3 className='text-3xl font-bold'>Pokemon Tower Defense</h3>
              <p className='pt-4 pb-4 text-2xl font-medium'>
                A remake of the original game, right in your browser!
              </p>
            </div>
            </Link>
          </div>

          <div>
            <Link href="/dnd" className={styles.childrenChangeOnHoverDnd}>
            <div className='text-center shadow-xl shadow-teal-800 p-10 rounded-xl my-10 flex items-center justify-center h-96 flex-col'>
              <ShieldIcon className="mx-auto text-3xl w-20 h-20"/>
              <h3 className='text-3xl font-bold'>DND Web App</h3>
              <p className='pt-4 pb-2 text-2xl font-medium'>
                Full stack web application built with node.js.
              </p>
            </div>
            </Link>
          </div>

          <div>
              <Link href="/pokemon-wpf" className={styles.childrenChangeOnHoverFarm}>
                <div className='text-center shadow-xl shadow-teal-800 p-10 rounded-xl my-10 flex items-center justify-center h-96 flex-col'>
                    <GiFarmTractor className='mx-auto text-3xl w-20 h-20' />
                    <h3 className='text-3xl font-bold'>Farming Android App</h3>
                    <p className='pt-4 pb-2 text-2xl font-medium'>
                      Full stack Android application made with Java in AndroidStudio.
                    </p>
                  </div>
            </Link>
          </div>

          <div>
              <Link href="/pokemon-wpf" className={styles.childrenChangeOnHoverPokemon}>
                <div className='text-center shadow-xl shadow-teal-800 p-10 rounded-xl my-10 flex items-center justify-center h-96 flex-col'>
                    <CatchingPokemon className='mx-auto text-3xl w-20 h-20' />
                    <h3 className='text-3xl font-bold'>Pokemon WPF</h3>
                    <p className='pt-4 pb-2 text-2xl font-medium'>
                      Full stack WPF application built with the fundamentals of OOP.
                    </p>
                  </div>
            </Link>
          </div>

          <div>
              <Link href="/" className={styles.childrenChangeOnHoverPokemon}>
                <div className='text-center shadow-xl shadow-teal-800 p-10 rounded-xl my-10 flex items-center justify-center h-96 flex-col'>
                    <AiOutlineTrophy className='mx-auto text-3xl w-20 h-20' />
                    <h3 className='text-3xl font-bold'>Other Smaller Projects</h3>
                    <p className='pt-4 pb-2 text-2xl font-medium'>
                      Click to see smaller projects that further demonstrate my skillset.
                    </p>
                  </div>
            </Link>
          </div>

        </section>
      </main>
    </>
  );
}
