import Navbar from "@/components/navbar";
import Head from "next/head";
import Image from "next/image";
import design from "../../public/design.png";

export default function Projects(){
    return(
        <>
      <Head>
        <title>Samuel Anderson Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-10">
          <Navbar/>
        <section>
        <div>
            <div className="text-center shadow-xl shadow-teal-800 p-10 rounded-xl my-10">
              <Image
                className="mx-auto"
                src={design}
                width={100}
                height={100}
              />
              <h3 className="text-lg font-medium">Projects Page!</h3>
              <p className="pt-4 pb-2">
                I create full-stack web <span className=" text-teal-700">//</span> desktop{" "}
                <span className=" text-teal-700">//</span> mobile applications
              </p>
              <h4>Tools I Use:</h4>
              <p className="text-gray-200 py-1">ASP.NET</p>
              <p className="text-gray-200 py-1">React</p>
              <p className="text-gray-200 py-1">Angular</p>
              <p className="text-gray-200 py-1">Javascript</p>
              <p className="text-gray-200 py-1">.NET MAUI</p>
              <p className="text-gray-200 py-1">Android Studio</p>
            </div>
          </div>
        </section>
      </main>
    </>
    );
}